### ISSUE TITLE
De-emphasize the size of development builds

### ISSUE THREAD

**Issue by gaearon** [elijahmanor/react-file-size#6]
To people choosing a library, it's not obvious that the huge size (700 kB) is referring to an unminified development builds with comments, warnings, etc. It would be great if the chart de-emphasized the size of development builds. In fact I'd remove them from the chart altogether because they are irrelevant to real deployments. But if you'd rather keep them, I'd either hide them behind a checkbox that's off by default, or put them on a separate chart that's clearly labeled.

**Comment by elijahmanor** [comment]
I have created a Development / Production toggle that defaults to Prod mode when displaying data in the chart below. I hope this helps de-emphasize the development size of the files.

Thanks for your feedback, it is very much appreciated. I really enjoy using React and want to make sure I represent it well to the community.

Here is the updated version http://elijahmanor.com/react-file-size/

NOTE: You may need to reset your cache locally until I put a mechanism to bust the cache automatically

**Comment by gaearon** [comment]
Thanks for addressing this so fast!
Two minor issues:

* It's a bit odd that clicking the currently selected toggle selects the other one. I would expect them to not do anything when clicked twice.
* I can't see `react-dom.min.gz` at all (the green line), did it get lost?

**Comment by elijahmanor** [comment]
@gaearon I fixed the green line not showing and added a cache buster so you shouldn't have to clear your cache. It will also dynamically pull from cdnjs for it's source instead of me having to go in and add a version number to an internal array. So future deploys (for updates) should be quicker.

As for the toggle button, that is a CSS trick that uses one checkbox under the covers to handle the state, but I agree the UX is not optimal for that. I'll create an issue to replace that with something else

**Comment by elijahmanor** [comment]
@gaearon I created issue #8 to address the toggle UX. If you have any other thoughts please feel free to ping me and/or create an issue

**Comment by gaearon** [comment]
Nice, thank you!
